version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/stop_apache_server.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/start_apache_server.sh
      timeout: 300
      runas: root

